// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9OhVlNdcFwG2p8FgA8ge5pTykRIoGkt8',
    appId: '1:938193404358:web:66e9a3d1484d2805af72c7',
    messagingSenderId: '938193404358',
    projectId: 'app-empresas-f603c',
    authDomain: 'app-empresas-f603c.firebaseapp.com',
    storageBucket: 'app-empresas-f603c.appspot.com',
    measurementId: 'G-1JF87XTN3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpWGiSkt6n-_5W5ie-RoEvLncrLjuTMHw',
    appId: '1:938193404358:android:02c4ad7d63b4a914af72c7',
    messagingSenderId: '938193404358',
    projectId: 'app-empresas-f603c',
    storageBucket: 'app-empresas-f603c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr11Nu6Ak-4JZhHdg9sxQ_3RvrGJcSG-A',
    appId: '1:938193404358:ios:07085168a0dc563baf72c7',
    messagingSenderId: '938193404358',
    projectId: 'app-empresas-f603c',
    storageBucket: 'app-empresas-f603c.appspot.com',
    iosClientId: '938193404358-sl8cravh0fc86egjc7gb1f0r1rch6oo1.apps.googleusercontent.com',
    iosBundleId: 'cl.bancoestado.empresas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr11Nu6Ak-4JZhHdg9sxQ_3RvrGJcSG-A',
    appId: '1:938193404358:ios:1028a57c960612e3af72c7',
    messagingSenderId: '938193404358',
    projectId: 'app-empresas-f603c',
    storageBucket: 'app-empresas-f603c.appspot.com',
    iosClientId: '938193404358-5c0nfei2g4ngv6g2duv8q7bn2e25vs0l.apps.googleusercontent.com',
    iosBundleId: 'cl.bancoestado.empresas.RunnerTests',
  );
}
